
[World-Generation]
	##forge:is_plains, Default=7
	flax1XZspread = 7
	##forge:is_desert and #forge:is_sandy, Default=15
	flax2Tries = 15
	##forge:is_plains, Default=4
	flax1Yspread = 4
	##forge:is_plains, Default=15
	flax1Tries = 15
	##forge:is_desert and #forge:is_sandy, Default=7
	flax2XZspread = 7
	##forge:is_desert and #forge:is_sandy, Default=4
	flax2Yspread = 4

[requires-game-restart]
	heavy_crossbow_durability = 625
	arbalest_durability = 825
	pistol_crossbow_durability = 415
	long_bow_durability = 455
	short_bow_durability = 310
	flat_bow_durability = 435
	recurve_bow_durability = 410

#Configure weapons conditions
[weapons]
	#Multiplier for the projectile speed for projectiles shot from  Pistol Crossbow, Default=0.65
	#Range: 0.1 ~ 3.4028234663852886E38
	pistol_crossbow_projectile_speed_multiplier = 0.6499999761581421
	#Multiplier for the projectile speed for projectiles shot from Short Bow, Default=0.8
	#Range: 0.1 ~ 100.0
	short_bow_projectile_speed_multiplier = 0.8
	#Flat Bow Drawspeed, Default=35
	#Range: 0.1 ~ 100.0
	flat_bow_drawspeed_modifier = 35.0
	#Pistol Crossbow Load Time, Default=10
	pistol_crossbow_load-time_modifier = 10
	#Recurve Bow Drawspeed, Default=20
	#Range: 0.1 ~ 100.0
	recurve_bow_drawspeed_modifier = 20.0
	#Multiplier for the projectile speed for projectiles shot from  Heavy Crossbow, Default=1.25
	#Range: 0.1 ~ 3.4028234663852886E38
	heavy_crossbow_projectile_speed_multiplier = 1.25
	#Arbalest Load Time, Default=70
	arbalest_load-time_modifier = 70
	#Multiplier for the projectile speed for projectiles shot from Arbalest, Default=1.45
	#Range: 0.1 ~ 3.4028234663852886E38
	arbalest_projectile_speed_multiplier = 1.4500000476837158
	#Multiplier for the projectile speed for projectiles shot from Long Bow, Default=1.65
	#Range: 0.1 ~ 100.0
	long_bow_projectile_speed_multiplier = 1.65
	#Multiplier for the projectile speed for projectiles shot from Recurve Bow, Default=1.15
	#Range: 0.1 ~ 100.0
	recurve_bow_projectile_speed_multiplier = 1.15
	#Long Bow Drawspeed, Default=50
	#Range: 0.1 ~ 100.0
	long_bow_drawspeed_modifier = 50.0
	#Heavy Crossbow Load Time, Default=45
	heavy_crossbow_load-time_modifier = 45
	#Short Bow Drawspeed, Default=15
	#Range: 0.1 ~ 100.0
	short_bow_drawspeed_modifier = 15.0
	#Multiplier for the projectile speed for projectiles shot from Flat Bow, Default=1.35
	#Range: 0.1 ~ 100.0
	flat_bow_projectile_speed_multiplier = 1.350000023841858

