
[model_options]
	#Slot 1
	s1 = false
	#Slot 2
	s2 = false
	#Slot 3
	s3 = false
	#Slot 4
	s4 = false
	#Slot 5
	s5 = false
	#Slot 6
	s6 = false
	#Slot 7
	s7 = false
	#Slot 8
	s8 = false
	#Slot 9
	s9 = false
	#Shield
	shield = true
	#Banner
	banner = true
	#Players can hide items
	canhideitems = true
	#Players can change the position and rotation of the displayed items
	can_change_pos_and_rot = true
	#Players can change the attachment of the slots
	can_change_attachment = true
	#Body part attachment to a slot
	attachment = "1-rleg,2-body,3-body,4-lleg,5-rleg,6-lleg,7-body,8-body,9-rleg,shield-body,banner-head"
	#Which active slot and equipment should move the item model away
	slot_mover = "none,legs;z;+_none,chest;z;+_none,legs;x;-_none,legs;x;+_none,legs,3;x;-_none,legs,4;x;+_none,chest,legs,1;z;+_none,shield;z;+_none,legs,3,5;x;-_none;z;-_none;z;-"
	#Whitelists item that are normally not visible
	whitelist = "empty,totem_of_undying"
	#Blacklists item that are normally visible
	blacklist = "empty"
	#Force server blacklist to players
	serverblacklist = false
	#Force server whitelist to players
	serverwhitelist = false

	[model_options.positions_rotations]
		#x position0
		#Range: > -2147483648
		x_position0 = -33
		#y position1
		#Range: > -2147483648
		y_position1 = 16
		#z position2
		#Range: > -2147483648
		z_position2 = -26
		#x rotation0
		#Range: > -2147483648
		x_rotation0 = 102
		#y rotation1
		#Range: > -2147483648
		y_rotation1 = 97
		#z rotation2
		#Range: > -2147483648
		z_rotationn2 = -33
		#x position3
		#Range: > -2147483648
		x_position3 = 4
		#y position4
		#Range: > -2147483648
		y_position4 = 24
		#z position5
		#Range: > -2147483648
		z_position5 = 3
		#x rotation3
		#Range: > -2147483648
		x_rotation3 = 0
		#y rotation4
		#Range: > -2147483648
		y_rotation4 = 86
		#z rotation5
		#Range: > -2147483648
		z_rotationn5 = 57
		#x position6
		#Range: > -2147483648
		x_position6 = -26
		#y position7
		#Range: > -2147483648
		y_position7 = 22
		#z position8
		#Range: > -2147483648
		z_position8 = 3
		#x rotation6
		#Range: > -2147483648
		x_rotation6 = -40
		#y rotation7
		#Range: > -2147483648
		y_rotation7 = 76
		#z rotation8
		#Range: > -2147483648
		z_rotationn8 = 90
		#x position9
		#Range: > -2147483648
		x_position9 = 26
		#y position10
		#Range: > -2147483648
		y_position10 = -11
		#z position11
		#Range: > -2147483648
		z_position11 = 20
		#x rotation9
		#Range: > -2147483648
		x_rotation9 = 0
		#y rotation10
		#Range: > -2147483648
		y_rotation10 = -87
		#z rotation11
		#Range: > -2147483648
		z_rotationn11 = 20
		#x position12
		#Range: > -2147483648
		x_position12 = 1
		#y position13
		#Range: > -2147483648
		y_position13 = -24
		#z position14
		#Range: > -2147483648
		z_position14 = 0
		#x rotation12
		#Range: > -2147483648
		x_rotation12 = 0
		#y rotation13
		#Range: > -2147483648
		y_rotation13 = -90
		#z rotation14
		#Range: > -2147483648
		z_rotationn14 = -30
		#x position15
		#Range: > -2147483648
		x_position15 = 31
		#y position16
		#Range: > -2147483648
		y_position16 = -24
		#z position17
		#Range: > -2147483648
		z_position17 = 0
		#x rotation15
		#Range: > -2147483648
		x_rotation15 = 0
		#y rotation16
		#Range: > -2147483648
		y_rotation16 = -90
		#z rotation17
		#Range: > -2147483648
		z_rotationn17 = -30
		#x position18
		#Range: > -2147483648
		x_position18 = 4
		#y position19
		#Range: > -2147483648
		y_position19 = 32
		#z position20
		#Range: > -2147483648
		z_position20 = -1
		#x rotation18
		#Range: > -2147483648
		x_rotation18 = 98
		#y rotation19
		#Range: > -2147483648
		y_rotation19 = 84
		#z rotation20
		#Range: > -2147483648
		z_rotationn20 = -51
		#x position21
		#Range: > -2147483648
		x_position21 = -2
		#y position22
		#Range: > -2147483648
		y_position22 = 20
		#z position23
		#Range: > -2147483648
		z_position23 = 45
		#x rotation21
		#Range: > -2147483648
		x_rotation21 = 0
		#y rotation22
		#Range: > -2147483648
		y_rotation22 = -84
		#z rotation23
		#Range: > -2147483648
		z_rotationn23 = 45
		#x position24
		#Range: > -2147483648
		x_position24 = 1
		#y position25
		#Range: > -2147483648
		y_position25 = -14
		#z position26
		#Range: > -2147483648
		z_position26 = 20
		#x rotation24
		#Range: > -2147483648
		x_rotation24 = 0
		#y rotation25
		#Range: > -2147483648
		y_rotation25 = -90
		#z rotation26
		#Range: > -2147483648
		z_rotationn26 = 20
		#x position27
		#Range: > -2147483648
		x_position27 = 0
		#y position28
		#Range: > -2147483648
		y_position28 = -16
		#z position29
		#Range: > -2147483648
		z_position29 = 14
		#x rotation27
		#Range: > -2147483648
		x_rotation27 = 2
		#y rotation28
		#Range: > -2147483648
		y_rotation28 = 0
		#z rotation29
		#Range: > -2147483648
		z_rotationn29 = 0
		#x position30
		#Range: > -2147483648
		x_position30 = 0
		#y position31
		#Range: > -2147483648
		y_position31 = -6
		#z position32
		#Range: > -2147483648
		z_position32 = -26
		#x rotation30
		#Range: > -2147483648
		x_rotation30 = 0
		#y rotation31
		#Range: > -2147483648
		y_rotation31 = 0
		#z rotation32
		#Range: > -2147483648
		z_rotationn32 = 0

